# Only Visual C++

image:
  - Visual Studio 2017

environment:
  matrix:
    ###
    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "ninja-vs-12-2013-win64"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013-win64"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "nmake-vs-12-2013"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-10-2010"
      CONFIG: Release

    - TOOLCHAIN: "vs-10-2010"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-11-2012"
      CONFIG: Release

    - TOOLCHAIN: "vs-11-2012"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013-win64"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-12-2013-xp"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013-xp"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Release

    - TOOLCHAIN: "vs-12-2013"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Release

    - TOOLCHAIN: "vs-14-2015"
      CONFIG: Debug

    ###
    - TOOLCHAIN: "vs-141-2017"
      CONFIG: Debug

    - TOOLCHAIN: "vs-141-2017"
      CONFIG: Release

    ###
    - TOOLCHAIN: "vs-9-2008"
      CONFIG: Release

    - TOOLCHAIN: "vs-9-2008"
      CONFIG: Debug